name = "reddrill"
main = ".open-next/worker.js"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

# Account ID - get from: wrangler whoami
# account_id = "your-account-id"

[observability]
enabled = true

# Static assets directory
[assets]
directory = ".open-next/assets"

# KV namespace for cache (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Cloudflare Workers AI binding for translation
[ai]
binding = "AI"
remote = true

# D1 Database for audit trail
[[d1_databases]]
binding = "DB"
database_name = "reddrill-audit"
database_id = "20330354-d122-4545-a309-11e6492c99d4"
migrations_dir = "drizzle"
